NCAR/geocat-examples

.gitignore, Plots/XY/README.rst
Adding some git ignores and a subdirectory for XY plot examples.
=> Updates to main repo structure

Plots/Vectors/README.rst, Plots/Vectors/vector1.py, Plots/Vectors/vector_1.py
@maboualidev and I converted [vector1.ncl](https://www.ncl.ucar.edu/Applications/Scripts/vector_1.ncl) to the python template. We use `contourf()` for the color contour of SST and `quiver()` for the vector plot.
=> Python version of vector1.ncl

conda_environment.yml
This package provides many (all?) of the colormaps available in ncl
=> Add cmaps to environment

Plots/Masking/README.rst, Plots/Masking/mask_1.py
Towards #13
- NCL Version:
- Python Version:
- NCL Version:
- Python Version:
=> Add Masking plots

Plots/Panels/README.rst, Plots/Panels/panel_1.py
=> Add panel_1

Plots/Contours/NCL_conLev_4.py
Replicates NCL's conLev_4 plot with a different colormap for now
=> Ncl_conLev4

.gitignore, Plots/Polygons/NCL_polyg_4.py, Plots/Polygons/README.rst
This is a work in progress.   Hatch patterns are hard to duplicate in matplotlib.
=> Add polyg_4 example

Plots/Trajectories/NCL_traj_1.py, Plots/Trajectories/README.rst
Issue #61. Plot created with randomly generated lat/long coordinates.
=> created trajectory plot for example traj_1

Plots/Panels/NCL_panel_35.py
References issue number #60.
Here is the plot in it's current state.
=> Adding panel_35 example python file

Plots/Contours/NCL_polar_1_lg.py
Closes issue [#58](https://github.com/NCAR/GeoCAT-examples/issues/58)
=> Adding NCL_polar_1_lg.py example python file 

Plots/XY/NCL_xy_3.py
=> Created xy_3 example

Plots/XY/NCL_xy_5.py
=> Adding xy_5 python example

Plots/Overlays/NCL_overlay_6.py
=> Adding overlay_6 python example

Plots/XY/NCL_xy_16.py
=> xy_16 example

Plots/Overlays/NCL_overlay_6.py
This PR fixes a potentially problematic "NaN to zero" data manipulation that is overlooked and merged in the PR #99 .
=> Fixed a problematic NaN to zero data manipulation from previous merge

Plots/Masking/NCL_lcmask_1.py
=> Adding NCL_lcmask_1 example file

Plots/Contours/NCL_conOncon_2.py
=> conOncon_2

Plots/Shapefiles/NCL_shapefiles_1.py, Plots/Shapefiles/README.rst
=> shapefiles_1

Plots/Contours/NCL_conOncon_5.py, Plots/Trajectories/NCL_traj_1.py
=> ConOncon 5

Plots/MapProjections/NCL_native_2.py
=> Native_2 New

Plots/WRF/NCL_dataonmap_10.py, Plots/WRF/README.rst, Plots/WRF/conda_environment.yml
=> dataonmap_10

.github/workflows/build.yml
Signed-off-by: pilotchute <akootz@ucar.edu>
=> commenting out pull request target for build

Plots/MapProjections/NCL_maponly_1.py, Plots/MapProjections/NCL_native_1.py
Closes #308
NCL Plot: https://www.ncl.ucar.edu/Applications/Images/maponly_1_lg.png
Python Plot:
=> NCL_maponly_1.py

.github/dependabot.yml, README.md, conda_environment.yml, docs/citation.rst, docs/index.rst
Adds "how to cite" info into README.md and RTD docs.
Also adds `dependabot` as it has been working smoothly with geocat-comp.
=> Added citing info

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/example-request.md
Creates issue templates for:
- bug report
- example request
=> Create issue templates

docs/install.rst
Addresses #348 
This PR updates the RTD installation page by replacing it with the correct installation instructions in INSTALLATION.md.
=> Update RTD installation page

Plots/Boxplots/NCL_box_2.py
Fix box_2 formatting issue
NCL Script: https://www.ncl.ucar.edu/Applications/Scripts/box_2.ncl
NCL Plot: https://www.ncl.ucar.edu/Applications/Images/box_2_lg.png
Issue: #371
=> box_2_fix_format

GeoCAT-comp-examples/matplotlib/fourier_filter_example.py, conda_environment.yml
- fourier_filter function: https://github.com/NCAR/geocat-comp
=> fourier_filter_example

Plots/Contours/NCL_polar_1.py
Fix polar_1 labels order.
- Original NCL script: https://www.ncl.ucar.edu/Applications/Scripts/polar_1_lg.ncl
- Original NCL plot: https://www.ncl.ucar.edu/Applications/Images/polar_1_lg.png
=> fix labels

Plots/Overlays/NCL_overlay_12.py
- Original NCL script: https://www.ncl.ucar.edu/Applications/Scripts/overlay_12.ncl
- Original NCL plots: https://www.ncl.ucar.edu/Applications/Images/overlay_12_1_lg.png
=> Overlay 12

Plots/Contours/NCL_polar_1.py
- Original NCL script: https://www.ncl.ucar.edu/Applications/Scripts/polar_1.ncl
- Original NCL plot: https://www.ncl.ucar.edu/Applications/Images/polar_1_lg.png
=> fix polar_1 url

GeoCAT-comp-examples/matplotlib/climatology_average_example.py, GeoCAT-comp-examples/matplotlib/climatology_example.py
This PR adds an example script for the `geocat-comp` function `calendar_average`. The produced plot is shown below, and there is an explanation of what the plot shows in the beginning notes of the example.
=> Adding climatology_average example

.github/workflows/ci.yml
Addresses #426 
- Switched to micromamba for environment solving
Notes:
- Seems to have reduced the "Create conda environment" step from 10-20 minutes to 1-5 minutes.
=> Use mamba for CI

conda_environment.yml
Summary: pins geocat-viz version until new structure can be incorporated into this repo
=> Pin geocat-viz version

Gallery/TaylorDiagrams/NCL_taylor_2.py, Gallery/TaylorDiagrams/README.rst
Resolves issue #456 
Original NCL plot:
https://www.ncl.ucar.edu/Applications/Images/taylor_2_lg.png
Python plot:
=> Creating taylor_2 example

Gallery/Scatter/NCL_scatter_10.py
Resolves issue #454 
Original NCL plot:
https://www.ncl.ucar.edu/Applications/Images/scatter_10_lg.png
Python plot:
=> Scatter 10

conda_environment.yml
Signed-off-by: pilotchute <akootz@ucar.edu>
=> pinned matplotlib version <3.6 and pinned pint to <0.20

Gallery/Contours/NCL_conOncon_1.py
Added add_right_hand_axis() utility function to example. Also some small formatting changes: adding minor ticks on x-axis, using black contour labels, adjusting contour levels to match NCL, changing y-axis heights to match NCL, and adding figure label at the bottom of the plot.
Resolves issue #409 
New version of plot with above changes:
=> ConOncon 1 add_right_hand_axis

README.md
Quick update to the installation instructions link in the README.md file.
Closes #434
=> Update README.md installation link

Gallery/Contours/NCL_minmax_3.py
* Updates `NCL_minmax_3.py` example so that it runs again
* Moves `NCL_minmax_3.py` over to the gallery with the other NCL examples
Closes #514.
=> Update NCL_minmax_3 example and move it over to the gallery

README.md
Thanks for showing how to fix this @anissa111
=> Correct status badge

conda_environment.yml
=> Remove unneeded xarray version pin

.github/workflows/ci.yml
Add environment cache key to ci.yml configuration file to fix our environment caching trouble.
Closes #543.
=> Add environment cache key to CI config file

.github/workflows/ci.yml, conda_environment.yml
=> Add Python 3.12 and remove Python 3.8

.github/workflows/ci.yml
=> Add a timeout limit for CI

docs/install.rst
=> Update install.rst for clarity and to remove the broken link I missed

Gallery/Contours/NCL_conLev_1.py
=> Fix temperature units in NCL_conLev_1.py

Gallery/Contours/NCL_conLev_1.py, Gallery/Masking/NCL_lcmask_1.py, Gallery/Masking/NCL_mask_1.py, Gallery/Masking/NCL_mask_2.py, Gallery/Overlays/NCL_overlay_1.py, Gallery/Overlays/NCL_overlay_6.py, Gallery/Panels/NCL_dev_1.py, Gallery/Panels/NCL_dev_2.py, Gallery/Panels/NCL_panel_13.py, Gallery/Panels/NCL_panel_20.py, Gallery/Vectors/NCL_vector_1.py, Gallery/XY/NCL_xy_16.py, Gallery/XY/NCL_xy_3.py, Gallery/XY/NCL_xy_4.py, README.md
Address xarray deprecation of drop.
Also fixes the upstream CI badge link on the README. 
Closes #600.
=> Address xarray deprecation of drop

Gallery/TaylorDiagrams/NCL_taylor_2.py
No longer calling add_xgrid() or add_ygrid().
Might have to wait until next release before merge.
=> Taylor Diagram example update with new methods

conda_environment.yml
=> Pin SciPy version until we address changes

.github/workflows/ci.yml, .github/workflows/upstream-dev-ci.yml
Removes a micromamba version pin.
The upstream issue that prompted this was addressed.
=> Remove micromamba version pin

Gallery/Contours/NCL_polar_8.py
Adds a quiver key to NCL_polar_8.py for reference and to more closely replicate the original NCL plot.  
Closes #634
=> Add quiver key to NCL_polar_8.py

docs/conf.py
Relates to https://github.com/NCAR/geocat-planning/issues/16
Closes https://github.com/NCAR/geocat-planning/issues/18
=> Reconfigure analytics
