NCAR/geocat-examples

- .rtd_conda_environment.yml
- Plots/Contours/NCL_coneff_16.py
- conda_environment.yml
Added geocat-datafiles as conda dependency and modified NCL_coneff_16.py to use geocat.datafiles.get to fetch data files instead of using the `/data` submodule directory of this repository.
> Use geocat-datafiles for downloading data files

- .rtd_conda_environment.yml
- Plots/Contours/NCL_coneff_16.py
- conda_environment.yml
Added geocat-viz as conda dependency and modified `NCL_coneff_16.py` to use `make_byr_cmap()` from `geocat-viz` instead of from `Plots/Contours/util/make_byr_cmap.py`.
> Use geocat-viz for plotting utility functions

- Plots/XY/xy_7_2_lg.py
Towards #3
- Original NCL:
- Python Version:
> Add XY_7_2 plot

- Plots/Masking/mask_1.py
The xr_add_cyclic function defined in mask_1.py includes the 'encoding' keyword argument to the xarray.DataArray constructor that was deprecated as of Xarray 0.14 and was removed in 0.15.
I believe the xr_add_cyclic function will eventually go into geocat-viz, so we should make this change there as well.
> Fix xarray.DataArray keyword args in mask_1.py

- README.md
This makes it easy to monitor the status of readthedocs builds without needing to  check the main readthedocs webpage:
> Add GitHub action and ReadTheDocs badges

- Plots/XY/NCL_xy_16.py
- Plots/XY/NCL_xy_4.py
Closes #123 
The sphinx documentation formatting has been fixed for these two examples. I also added another item to the list of concepts illustrated by NCL_xy_4.py regarding drawing legends.
> Fix Sphinx documentation formatting in NCL_xy_16.py and NCL_xy_4.py

- conda_environment.yml
This PR adds geographiclib package dependency to conda environment in favor of PR #140
> Added geographiclib to conda_environment

- Plots/XY/NCL_xy_5.py
Closes #153 
In the NCL version of the xy_5 example, the datafile represents dates in a YYYYMM format. To make the plot, the NCL example first converts the dates into floats using a format where the decimal component represents a fraction of the year in place of months. 
The GeoCAT version of xy_5 uses another method to accurately plot the date while also converting the dates; however the fractional dates are never used and are also calculated incorrectly. This PR makes the GeoCAT example more accurate and consistent with the NCL one.
> Changing xy_5 to plot data using fractional dates

- Plots/Panels/NCL_panel_35.py
This PR fixes an issue in Plots/Panels/NCL_panel_35.py that was due to unmatching numbers of tick values and tick labels that are input into a helper function from geocat-viz repo. The issue occurred after matplotlib's newer version of 3.3.0.
PR handles the fix by equating the number of tick values and labels.
> Inconsistency between number of ticks and tick labels resolved

- Plots/Contours/NCL_polar_1_lg.py
NCL_polar_1.py originally from this PR #75 used hard coded values to position the longitude labels around the plot. A better method of doing this has been found, and it doesn't require any hard coding. This PR modifies NCL_polar_1.py to use the new method.
> Update NCL_polar_1.py implementation for drawing longitude labels

- Plots/Contours/NCL_conOncon_5.py
- Plots/Contours/NCL_polar_1_lg.py
- Plots/Masking/NCL_lcmask_1.py
- Plots/Panels/NCL_panel_6.py
Closes #91 
In addition to updating `NCL_lcmask_1.py` and `NCL_polar_1.lg.py`, this PR also updates `NCL_panel_6.py` and `NCL_conOncon_5.py` which use custom helper functions to draw circle boundaries for polar stereographic maps. Those examples were created after issue #91 and were not mentioned in it. The plots all appear the same as they did before this update.
> Updating examples to use geocat-viz set_map_boundary()

- .github/workflows/build.yml
Adds `pull_request_target` event into `.github/workflows/build.yml` per the following improvement from this [Github anouncement](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) :
"GitHub Actions has always been about more than just continuous integration. Our goal is to enable repository maintainers to automate a variety of workflows and reduce manual effort. In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets. This makes common workflows like labeling or commenting on pull requests very difficult.
In order to solve this, we’ve added a new `pull_request_target` event, which behaves in an almost identical way to the …
> Fix workflow not triggering from forked repo issue

- .github/workflows/build.yml
Addresses #292 
There is a ticket working its way through the action on github now, so I assume the issue will eventually be resolved by itself, but for now, to allow the commands ```add-path``` and ```set-env``` to run as before, I added the ```ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' ``` tag to the build.yml file as suggested in the error read out. This allows the two deprecated commands to still be used in our build process while the action we are using updates.
> Github actions build failures

- _templates/breadcrumbs.html
- index.rst
- support.rst
Addresses #298 
- overrides sphinx theme read the docs button
I have made the [sphinx_delete branch visible on RTD](https://geocat-examples.readthedocs.io/en/sphinx_delete/) so you can go look at how the change affects the documentation generation.
> Remove "Edit on Github" buttons from RTD builds

- .gitignore
- CONTRIBUTING.md
- GeoCAT-comp-examples/README.rst
- GeoCAT-comp-examples/comp_only/README.rst
- GeoCAT-comp-examples/comp_only/moc_globe_atl_example.py
- GeoCAT-comp-examples/matplotlib/README.rst
- GeoCAT-comp-examples/matplotlib/linint2_example.py
- GeoCAT-comp-examples/matplotlib/linint2pts_example.py
- Plots/README.rst
- Plots/WRF/NCL_WRF_zoom_1_2.py
- conf.py
- index.rst
This PR adds the usage example scripts from GeoCAT-comp (only `linint2`, `linint2pts`, and `moc_globe_atl` were implemented so far) to this gallery. It also makes several updates, paraphrasing, etc. related to this insertion. 
@michaelavs @anissa111 could you please look at the generated [webpage here](https://geocat-examples.readthedocs.io/en/geocat_comp_examples/) and let me know anything else you want to be changed (text, titles, hierarchy, etc.)
> Added GeoCAT-comp usage examples

- Plots/Polygons/NCL_polyg_2.py
- Plots/WRF/NCL_WRF_zoom_1_2.py
- README.md
- conda_environment.yml
After `cartopy`'s version 0.19.0 release, shape file errors occurred in two scripts, which are not occurring in local: 
- `NCL_polyg_2`: KeyError: "There is no item named 'ne_110m_admin_1_states_provinces_lakes_shp.cpg' in the archive" 
- `NCL_WRF_zoom_1_2`: KeyError: "There is no item named 'ne_50m_admin_1_states_provinces_shp.cpg' in the archive"
Above errors can be found in scheduled CI actions, e.g. [see this one](https://github.com/NCAR/GeoCAT-examples/runs/2442188579?check_suite_focus=true).
This PR downgrades `cartopy` to 0.18.0, and it seems to have worked. 
It also fixes CI link in Badge, which was accidentally linking to `geocat-comp`'s badge before.
> Downgrade cartopy to 0.18.0 to fix CI errors

- Plots/Panels/NCL_panel_19.py
Current panel 19 [script](https://geocat-examples.readthedocs.io/en/latest/gallery/Panels/NCL_panel_19.html#sphx-glr-gallery-panels-ncl-panel-19-py) is linked to wrong NCL script and plot.
- Original NCL script: https://www.ncl.ucar.edu/Applications/Scripts/panel_19.ncl
- Original NCL plot: https://www.ncl.ucar.edu/Applications/Images/panel_19_1_lg.png and https://www.ncl.ucar.edu/Applications/Images/panel_19_2_lg.png
> fix panel 19 links

- Plots/Panels/NCL_panel_14.py
I'm going to use this in my presentation when I noticed some differences between original plot and mine, so I changed the spacing between subplots, color bar aspect and padding.
- Original NCL script: http://www.ncl.ucar.edu/Applications/Scripts/panel_14.ncl
- Original NCL plot: http://www.ncl.ucar.edu/Applications/Images/panel_14_lg.png
> Fix panel_14 spacing and color bar

- conda_environment.yml
- unpins geocat-viz from 2020.07.0 to use the most recent version
> Unpin geocat-viz

- .github/workflows/ci.yml
- conda_environment.yml
Changed oldest supported Python version from 3.6 to 3.7. Updated dependency list accordingly. Changed ci workflow to check against Python versions 3.7 and 3.9 rather than 3.6 and 3.9.
> Bumped oldest python version from 3.6 to 3.7

- GeoCAT-comp-examples/matplotlib/calendar_average_example.py
This PR adds an example script for the `geocat-comp` function `calendar_average`. The produced plot is shown below, and there is an explanation of what the plot shows in the beginning notes of the example.
> Adding calendar_average example

- Plots/Skew-T/NCL_skewt_2_2.py
Closes #423 
This PR updates `NCL_skewt_2_2` to use the geocat-comp function `get_skewt_vars`. Currently geocat-viz does not have the ability to make a subtitle using `set_titles_and_labels`, so this PR implements a work around until the issue in GeoCAT-viz https://github.com/NCAR/geocat-viz/issues/52 is closed.
NCL Plot: 
Current GeoCAT Plot: ![image](https://user-images.githubusercontent.com/42781301/150019443-8054f0a3-090e-4880-9a89-6532bba5d457.png)
> Update `NCL_skewt_2_2` to have subtitle

- INSTALLATION.md
- docs/install.rst
Clarification on how to update and install geocat packages in a pre-existing environment was requested in this issue https://github.com/NCAR/GeoCAT/issues/43. After speaking with the user who suggested these changes, it was determined that she was looking at the geocat-comp documentation. These instructions are being added to the contributor's guide https://github.com/NCAR/GeoCAT/pull/47, but also should be added to each GeoCAT repository.
This PR updates the installation instructions so that INSTALLATION.md links to installation.rst for easier maintenance. It also adds instructions for how to ensure the environment is up to date.
> Updating installation instructions

- Gallery/Vectors/NCL_vector_1.py
- Gallery/Vectors/NCL_vector_3.py
- Gallery/Vectors/NCL_vector_4.py
`NCL_vector_1.py`, `NCL_vector_3.py`, and `NCL_vector_4.py` all had an issue with multiple axes. This PR fixes that bug by replacing `plt.subplots` with `plt.figure` since none of the scripts required multiple axes.
This bug is recent and the cause of it is still uncertain given that `matplotlib` has not had recent updates and the recently released `cartopy` [v0.20.3](https://github.com/SciTools/cartopy/releases/tag/v0.20.3) has no changes to `GeoAxes` in it's change log.
> Bug fix for multiple axes

- Gallery/MapProjections/NCL_native_1.py
Uses geocat-viz add_lat_lon_gridlines() utility function in example.
This resolves issue #410 
Python plot using util function:
> Native 1 add_lat_lon_gridlines

- .github/workflows/ci-nightly.yml
- .github/workflows/ci.yml
Addresses #473
- adds separate `ci-nightly.yml` workflow that runs on all `os` and `python-version`s at 1 AM nightly
- modifies `ci.yml` to cancel previous workflows and to run `macos-latest` on oldest and newest versions of python we support (3.7 and 3.10) to help concurrency limit (all versions run nightly)
> Reduce Concurrent Tests

- .github/workflows/ci-nightly.yml
- renames workflow from`ci-nightly.yml` from "CI" to "CI Nightly" to be distinct from the "CI" workflow coming from `ci.yml`
> Rename nightly workflow to be distinct

- Gallery/MapProjections/NCL_native_2.py
Uses geocat-viz add_lat_lon_gridlines() utility function for the example.
Resolves issue #410 
Python plot using function:
> Native_2 add_lat_lon_gridlines

- Gallery/Contours/NCL_ce_3_1.py
Creates NCL example ce_3_1 using geocat-viz Contour function. Includes link to previous version that does not use Contour.
Resolves issue #467 
[Previous script](https://geocat-examples.readthedocs.io/en/v2022.5.0/gallery/Contours/NCL_ce_3_1.html#sphx-glr-gallery-contours-ncl-ce-3-1-py)
Original NCL plot:
https://www.ncl.ucar.edu/Applications/Images/ce_3_1_lg.png
New version of plot using Contour:
> ce_3_1 with Contour

- Gallery/Skew-T/NCL_skewt_2_2.py
- Gallery/Skew-T/NCL_skewt_3_2.py
- conda_environment.yml
Addresses #481 
- remove units from `p` for `metpy.plot_barbs` call
- comments about making `p` unitless
Notes:
- Not clear why this started failing, other than it _might_ be connected to the newest sphinx (5.5.1) release on Wednesday.
- This change is, as far as I can tell, only reproducible by running `make html`. Neither `skewt_2_2` or `skewt_3_2` have had issues running locally outside of sphinx generation
- Might be a bug we should report to metpy.
> Fix for skewt plots

- conda_environment.yml
This PR pins the xarray version to <=2023.02.0 as the latest versoin of xarray is causing checks to fail. This is a temporary fix, see #495 for more details
> Pin xarray in conda_environment.yml

- Gallery/Contours/NCL_conwomap_3.py
- Gallery/Meteograms/NCL_meteo_1.py
- GeoCAT-comp-examples/comp_only/moc_globe_atl_example.py
Changes the deprecated `np.int` alias to `np.int32` per the guidance from numpy: 
https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
Opted to use `np.int32` rather than `int` for specificity.
Closes #510 .
> change deprecated np.int alias to np.int32

- conda_environment.yml
Unpin matplotlib version and remove old ncar channel from the conda env file.  I did double check that datafiles and wrf-python are both on conda-forge as well and we should be good.
Closes #517
> Unpin matplotlib and remove old ncar channel

- conda_environment.yml
- docs/gallery-notebooks/Datashader/MPAS_Datashader_Trimesh.ipynb
Adjust notebook plot sizing to look cleaner with the new theme.  
For context: I was hoping to be able to use the responsive options that would adjust with the window size, but unfortunately those don't seem to work well in this case.  I could only get the responsive width to work, but that was distorting the visualizations.  Setting the width in pixels to something that should look reasonable in most cases was a compromise.  
This PR also adds needed dependencies (e.g. geoviews, holoviews, datashader) to the environment so that everything builds with the clean notebook (no cells run ahead of time).  This may take a little longer to build for testing and obviously adds some dependencies so open to pulling this from the PR.  
Closes #519.
> Adjust notebook plot sizing

- GeoCAT-comp-examples/comp_only/moc_globe_atl_example.py
- GeoCAT-comp-examples/matplotlib/linint2_example.py
- GeoCAT-comp-examples/matplotlib/linint2pts_example.py
- conda_environment.yml
Adds geocat-f2py to the environment and changes references to geocat-f2py from comp for functions that were removed from comp in the comp / f2py disentanglement.  
Closes #525
> Fix references to geocat-f2py functions that were broken by the latest release of geocat-comp

- conda_environment.yml
- docs/_templates/breadcrumbs.html
- docs/conf.py
Clean up environment file to mitigate sphinx version problem:
* Removes old sphinx theme from the environment file and related template file
* Removes jupyter and sphinx from the environment file so they're just installed as dependencies (hopefully this mitigates the sphinx version issue we are having)
Closes #541.
> Clean up environment file to mitigate sphinx version problem

- Gallery/Animations/NCL_animate_1.py
Comment out saving the animation in NCL_animate_1.py to save some resources.  
Should help with #537, but we'll still need to do some additional work.
> Comment out saving the animation in NCL_animate_1.py

- Gallery/Vectors/NCL_vector_3.py
Better document usage of set_vector_density in NCL_vector_3.py and change the input to the proper type and a more reasonable value that shouldn't produce a warning.
Closes #534.
> Better document usage of set_vector_density in NCL_vector_3.py

- Gallery/Animations/NCL_animate_1.py
- Gallery/Colors/CB_Height.py
- Gallery/Colors/CB_Rain.py
- Gallery/Colors/CB_Temperature.py
- Gallery/Masking/NCL_mask_5.py
- Gallery/Vectors/NCL_vector_1.py
Either adjusts the contouring to align with the assigned labels or for the animation example turns off the minor ticks.
Some minor updates to comments in the animation example as well to reflect prior changes.
Closes #574
> Adjust contour levels and colorbar ticks to adapt to updates in Matplotlib 3.6+

- Gallery/Polygons/NCL_polyg_19.py
- Gallery/Polygons/NCL_polyg_4.py
A couple of minor changes for matplotlib 3.8+ compatibility (all backward compatible):
* Changes the way an argument is specified (positional to keyword)
* Adjusts the way contour labels are specified to avoid an error
Closes #578
> Matplotlib 3.8+ compatibility - positional to keyword args and contour label specification fixes

- .github/workflows/upstream-dev-ci.yml
- ci/install-upstream.sh
- conda_environment.yml
Adds upstream CI based upon what @anissa111 set up for geocat-comp and xarray's upstream CI.  Includes geocat-viz and geocat-comp along with some key dependencies.  
I was able to run this on my fork, but didn't realize turning off actions would break the link to prior runs.  Let me know if you'd like me to turn it back on so you can check out some runs / logs.
I think this is probably a good start, but do wonder if it might catch "too much" the way it's currently configured (e.g. the frequency of testing and number of upstream dev packages we're testing).     
We could also think about adding some sort of automation to generate issues when this fails.  xarray and matplotlib both have this set up in slightly different ways.  xarray's is a bit custom, but some other packages are using it …
> Add upstream CI

- README.md
Adds an upstream CI status badge to README.md and cleans up some of the associated links / formatting.
Closes #582.
> Add upstream CI status badge to README.md

- conda_environment.yml
Pins Sphinx < 7 to address the broken gallery links / thumbnail issues (for the time being).
I'd like to understand a bit better what's going on so we can address it more fully and/or log some issues, but building the gallery locally is a bit challenging at the moment (because of wrf-python).
Relates to #587.
> Pin Sphinx version to address gallery issues

- Gallery/Scatter/NCL_scatter_10.py
- Gallery/Topography/NCL_topo_8.py
- conda_environment.yml
Addresses a few problems caught by testing with Python 3.12:
* an unnecessary import that will no longer work
* fix some shapefile reads that now break 
* add dask to the conda env because xarray needs it in at least one of our examples
We'll still need to wait on a few dependencies for Python 3.12, but these are probably good to get in anyway.
Related to #550.
> Address a few problems caught by testing with Python 3.12

- .github/workflows/ci.yml
Changes our CI to use macos-13 runners in order to keep testing on Intel-based Macs until our dependencies support running on Apple silicon (see #604).
> Use macos-13 runners to keep testing on Intel-based Macs

- Gallery/MapProjections/NCL_sat_1.py
- Gallery/MapProjections/NCL_sat_2.py
- Gallery/MapProjections/NCL_sat_3.py
Adjusts the three satellite projection examples to better mimic NCL's satellite projection using Cartopy's [NearsidePerspective](https://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html#cartopy.crs.NearsidePerspective) (which allow for a satellite_height option) and [Orthographic](https://scitools.org.uk/cartopy/docs/v0.15/crs/projections.html#orthographic) (equivalent in certain cases) projections.
Closes #602.
> Better mimic NCL's satellite projection

- .github/workflows/ci.yml
- .github/workflows/upstream-dev-ci.yml
Pins micromamba temporarily while upstream issues are addressed: https://github.com/mamba-org/setup-micromamba/issues/225
This should get our CI passing again though upstream-dev will still be failing because of the SciPy changes.
Also, updates the frequency for upstream-dev CI to weekly.  Realistically, I don't think we're addressing issues fast enough to warrant anything more frequent.
> pins micromamba and update the frequency for upstream-dev CI

- Gallery/Vectors/NCL_vector_5.py
- conda_environment.yml
Addresses the SciPy `interp2d` deprecation by using xarray's `interp` method instead.
Closes #607
This doesn't address the bigger issues I stumbled upon in looking into this of matplotlib's streamlines requiring input data on a regular grid (this should probably be addressed as an upstream contribution) and that these (streamlines vs NCL curly vectors) are different ways of representing data.  While they look similar, they aren't showing information in the same ways and that should probably be documented.  The reference vector is also incorrect.  I'll log this as an issue.
> Address SciPy interp2d deprecation

- Gallery/Contours/NCL_hov_3.py
- Gallery/Overlays/NCL_overlay_11b.py
- Gallery/XY/NCL_xy_16.py
Addresses several of the failures we're seeing while testing with a dev version of Matplotlib (3.10.0.dev).   
These stem from deprecations following earlier Matplotlib changes with `ContourSet` and `legend`.
Relates to #620
There will be a lingering problem related to hatch color that this PR does not address so I'm leaving the associated issue open for now.  There's also an open issue (confirmed bug) on Matplotlib.
> Address CI failures from upstream Matplotlib changes

- docs/conf.py
Merges theme configuration dictionaries to address issues cause by the second dictionary overwriting the first.
> Theme configuration fix

- conda_environment.yml
Exclude xarray version with the seaborn import bug mentioned in #627.  Since there's already a fix, the next release should be fine (i.e. no need to further constrain the version).
Closes #627
> Avoid Xarray version w/ bug

- Gallery/Contours/NCL_coneff_11.py
- Gallery/Contours/NCL_hov_3.py
Addresses lingering issues to support Matplotlib 3.10 (after these go in our upstream CI should no longer be failing).
Changes are all related to setting contour plot properties now that ContourSet has moved to a single Collection.
Closes #620
> Remaining changes to support Matplotlib 3.10

- .readthedocs.yml
- CODE_OF_CONDUCT.md
Updates the Read the Docs configuration to add explicit configuration of Sphinx.
See here for more info: https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
> Update docs config

- ci/install-upstream.sh
Removes NumPy from upstream-dev CI since it's pinned by other dependencies anyway and now causing environment issues with upstream-dev CI.
It looks like we are getting the dev versions of the other packages so I'll leave those as is.  
Closes #637
> Remove NumPy from upstream-dev CI

- CODE_OF_CONDUCT.md
Updates the Code of Conduct for consistency with the new organizational template.
So long as folks are ok with this, I'll go ahead an update the other repos as well.
And in case anyone else catches it, there is a broken link on the template website that should link to the UCAR Participant CoC.  This has been reported to the folks who maintain the site.
> Code of Conduct update

- .github/workflows/ci.yml
- .github/workflows/upstream-dev-ci.yml
Pins third party GitHub Actions to commit hashes and drops the retry timeout to 20 mins to save some runtime.
Closes #645
> GitHub Actions pin updates

- .pre-commit-config.yaml
- Gallery/Bar/NCL_bar_2.py
- Gallery/Bar/NCL_bar_4.py
- Gallery/Boxplots/NCL_box_1.py
- Gallery/Boxplots/NCL_box_3.py
- Gallery/Contours/NCL_conLev_1.py
- Gallery/Contours/NCL_conLev_3.py
- Gallery/MapProjections/NCL_maponly_6.py
- Gallery/MapProjections/NCL_native_1.py
- Gallery/MapProjections/NCL_native_2.py
- Gallery/MapProjections/NCL_sat_1.py
- Gallery/Overlays/NCL_overlay_1.py
- Gallery/Overlays/NCL_overlay_6.py
- Gallery/Panels/NCL_panel_10.py
- Gallery/Panels/NCL_panel_6.py
- Gallery/XY/NCL_tm_2.py
- Gallery/XY/NCL_xy_12.py
- Gallery/XY/NCL_xy_16.py
- Gallery/XY/NCL_xy_18.py
- Gallery/XY/NCL_xy_5.py
- Gallery/XY/NCL_xy_7_2.py
- docs/install.rst
- template_script.py
Fix code misspellings with `codespell`, as part of the transition to ruff
Related to #619
> codespell pre-commit
